export type Artists = "postmalone";

export type Cities =
  | "Mansfield"
  | "Hartford"
  | "Camden"
  | "Bristow"
  | "Charlotte"
  | "West Palm Beach"
  | "Tampa"
  | "Atlanta"
  | "Dallas"
  | "Houston"
  | "Albuquerque"
  | "Phoenix"
  | "San Diego"
  | "Wheatland"
  | "Mountain View"
  | "San Bernardino"
  | "Santiago"
  | "Curitiba"
  | "ISão Paulo"
  | "Mexico City"
  | "Bangkok"
  | "Singapore"
  | "Manila"
  | "Taipei"
  | "Seoul"
  | "Hong Kong"
  | "Tokyo"
  | "Auckland"
  | "Brisbane"
  | "Canberra"
  | "Mitchell"
  | "Gold Coast"
  | "Carrara"
  | "Sydney"
  | "Melbourne"
  | "Ballarat"
  | "Newington"
  | "Perth"
  | "Claremont";
